self="$BASH_SOURCE"
rootDir=$(dirname "$(dirname "$self")")

mkdir -p /tmp/$USER

export MACPORTS_PREFIX=/opt/local
export CLICOLOR=1
export LSCOLORS=GxFxCxDxBxegedabagaced

# User specific aliases and functions
export PS1='[\u@\h \W]\$ '

export M2_HOME=$HOME/lib/maven
export JAVA_HOME=$HOME/lib/java

PATH=/usr/local/bin:$PATH
PATH=/usr/local/sbin:$PATH
PATH=$M2_HOME/bin:$PATH
PATH=$JAVA_HOME/bin:$PATH
PATH=$HOME/lib/scala/bin:$PATH
PATH=$HOME/bin:$PATH
PATH=$HOME/lib/sbt/bin:$PATH
PATH=$HOME/lib/ant/bin:$PATH
PATH=$HOME/lib/kafka/bin:$PATH
PATH=$rootDir/bin:$PATH

if [[ -d $HOME/.bashrc.d ]]
then
  for script in $(find $HOME/.bashrc.d -type f)
  do
    . $script
  done
fi

if [[ -f "$PWD/bash_profile" ]]
then
  source "$PWD/bash_profile"
  prj="${PROJECT_NAME:-$(basename "$PWD")}"
  export PS1="[\e[1;31m$prj\e[m \W]$ "
fi
